version: "2.4"
#networks:
#  software:
#    name: network-project
#    external: true
networks:
  software:
    name: network-config-server
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1

services:
  ms-config-server:
    image: ms-config-server:0.0.4
    mem_limit: 200m
    ports:
      - "8887:8887"
    networks:
      - software
    volumes:
      - "D:/Semestre 2-2021/Arquitectura del SW/tarea/logs/ms-config-server:/opt/arquitectura/logs"
    environment:
      - "EUREKA_URI=http://ms-discovery:8763/eureka"